# Generated by Django 3.0.2 on 2020-01-17 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('thumbnail', models.ImageField(blank=True, upload_to='blog/static/img', verbose_name='Thumbnail')),
                ('content', models.TextField(verbose_name='Content')),
                ('published', models.DateTimeField(default=datetime.datetime.now, verbose_name='date published')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
