# Generated by Django 3.0.2 on 2020-01-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200126_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='avatar',
            field=models.ImageField(blank=True, height_field=200, null=True, upload_to='blog/static/img/avatar', verbose_name='Avatar', width_field=200),
        ),
    ]
